use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'RollingKit_Example' do

pod 'RollingKit', path: '../'

end

target 'RollingKit_Tests' do

inherit! :search_paths

pod 'RollingKit', path: '../'
pod 'Quick', '~> 1.2.0'
pod 'Nimble', '~> 7.0.2'
pod 'FBSnapshotTestCase' , '~> 2.1.4'
pod 'Nimble-Snapshots' , '~> 6.3.0'

end
